import Foundation

/// Represents a single predictive text suggestion generated by the NLP pipeline.
struct Suggestion: Equatable {
    /// The predicted text to display as ghost text.
    let text: String

    /// Confidence score from 0.0 to 1.0.
    let confidence: Double

    /// The source algorithm that produced this suggestion.
    let source: SuggestionSource

    /// The character position in the document where this suggestion should be inserted.
    let insertionOffset: Int

    /// Timestamp when the suggestion was generated (for staleness checks).
    let timestamp: Date

    init(
        text: String,
        confidence: Double,
        source: SuggestionSource,
        insertionOffset: Int,
        timestamp: Date = Date()
    ) {
        self.text = text
        self.confidence = confidence
        self.source = source
        self.insertionOffset = insertionOffset
        self.timestamp = timestamp
    }

    /// Returns true if this suggestion is still fresh enough to display (< 3 seconds old).
    var isFresh: Bool {
        Date().timeIntervalSince(timestamp) < 3.0
    }
}

/// The algorithm that generated a prediction.
enum SuggestionSource: String, Equatable {
    /// Frequency-based n-gram lookup from the local language model.
    case ngram = "N-Gram"

    /// Semantic similarity via NLEmbedding word vectors.
    case embedding = "Embedding"

    /// Combined n-gram + embedding fusion.
    case hybrid = "Hybrid"
}

/// Observable state machine for the suggestion lifecycle.
enum SuggestionState: Equatable {
    /// No prediction in progress.
    case idle

    /// Prediction is being computed asynchronously.
    case loading

    /// A suggestion is ready to be rendered as ghost text.
    case ready(Suggestion)

    /// The user dismissed the current suggestion.
    case dismissed
}
